package POJOS;
// Generated 05-mar-2025 14:16:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Contribuyente generated by hbm2java
 */
public class Contribuyente  implements java.io.Serializable {


     private int idContribuyente;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private String nifnie;
     private String direccion;
     private String numero;
     private String paisCcc;
     private String ccc;
     private String iban;
     private String email;
     private Double bonificacion;
     private String ayuntamiento;
     private Set reciboses = new HashSet(0);
     private Set vehiculoses = new HashSet(0);

    public Contribuyente() {
    }

	
    public Contribuyente(int idContribuyente, String nombre, String apellido1, String nifnie, String direccion, String ayuntamiento) {
        this.idContribuyente = idContribuyente;
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.nifnie = nifnie;
        this.direccion = direccion;
        this.ayuntamiento = ayuntamiento;
    }
    public Contribuyente(int idContribuyente, String nombre, String apellido1, String apellido2, String nifnie, String direccion, String numero, String paisCcc, String ccc, String iban, String email, Double bonificacion, String ayuntamiento, Set reciboses, Set vehiculoses) {
       this.idContribuyente = idContribuyente;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.nifnie = nifnie;
       this.direccion = direccion;
       this.numero = numero;
       this.paisCcc = paisCcc;
       this.ccc = ccc;
       this.iban = iban;
       this.email = email;
       this.bonificacion = bonificacion;
       this.ayuntamiento = ayuntamiento;
       this.reciboses = reciboses;
       this.vehiculoses = vehiculoses;
    }
   
    public int getIdContribuyente() {
        return this.idContribuyente;
    }
    
    public void setIdContribuyente(int idContribuyente) {
        this.idContribuyente = idContribuyente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public String getNifnie() {
        return this.nifnie;
    }
    
    public void setNifnie(String nifnie) {
        this.nifnie = nifnie;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getPaisCcc() {
        return this.paisCcc;
    }
    
    public void setPaisCcc(String paisCcc) {
        this.paisCcc = paisCcc;
    }
    public String getCcc() {
        return this.ccc;
    }
    
    public void setCcc(String ccc) {
        this.ccc = ccc;
    }
    public String getIban() {
        return this.iban;
    }
    
    public void setIban(String iban) {
        this.iban = iban;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Double getBonificacion() {
        return this.bonificacion;
    }
    
    public void setBonificacion(Double bonificacion) {
        this.bonificacion = bonificacion;
    }
    public String getAyuntamiento() {
        return this.ayuntamiento;
    }
    
    public void setAyuntamiento(String ayuntamiento) {
        this.ayuntamiento = ayuntamiento;
    }
    public Set getReciboses() {
        return this.reciboses;
    }
    
    public void setReciboses(Set reciboses) {
        this.reciboses = reciboses;
    }
    public Set getVehiculoses() {
        return this.vehiculoses;
    }
    
    public void setVehiculoses(Set vehiculoses) {
        this.vehiculoses = vehiculoses;
    }




}


