package POJOS;
// Generated 05-mar-2025 14:16:40 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Recibos generated by hbm2java
 */
public class Recibos  implements java.io.Serializable {


     private int numRecibo;
     private Contribuyente contribuyente;
     private Vehiculos vehiculos;
     private Date fechaPadron;
     private Date fechaRecibo;
     private String nifContribuyente;
     private String direccionCompleta;
     private String iban;
     private String tipoVehiculo;
     private String marcaModelo;
     private String unidad;
     private double valorUnidad;
     private double totalRecibo;
     private Character exencion;
     private double bonificacion;
     private String email;
     private String ayuntamiento;

    public Recibos() {
    }

	
    public Recibos(int numRecibo, Contribuyente contribuyente, Vehiculos vehiculos, Date fechaPadron, Date fechaRecibo, String nifContribuyente, String direccionCompleta, String tipoVehiculo, String marcaModelo, String unidad, double valorUnidad, double totalRecibo, String ayuntamiento) {
        this.numRecibo = numRecibo;
        this.contribuyente = contribuyente;
        this.vehiculos = vehiculos;
        this.fechaPadron = fechaPadron;
        this.fechaRecibo = fechaRecibo;
        this.nifContribuyente = nifContribuyente;
        this.direccionCompleta = direccionCompleta;
        this.tipoVehiculo = tipoVehiculo;
        this.marcaModelo = marcaModelo;
        this.unidad = unidad;
        this.valorUnidad = valorUnidad;
        this.totalRecibo = totalRecibo;
        this.ayuntamiento = ayuntamiento;
    }
    public Recibos(int numRecibo, Contribuyente contribuyente, Vehiculos vehiculos, Date fechaPadron, Date fechaRecibo, String nifContribuyente, String direccionCompleta, String iban, String tipoVehiculo, String marcaModelo, String unidad, double valorUnidad, double totalRecibo, Character exencion, Character bonificacion, String email, String ayuntamiento) {
       this.numRecibo = numRecibo;
       this.contribuyente = contribuyente;
       this.vehiculos = vehiculos;
       this.fechaPadron = fechaPadron;
       this.fechaRecibo = fechaRecibo;
       this.nifContribuyente = nifContribuyente;
       this.direccionCompleta = direccionCompleta;
       this.iban = iban;
       this.tipoVehiculo = tipoVehiculo;
       this.marcaModelo = marcaModelo;
       this.unidad = unidad;
       this.valorUnidad = valorUnidad;
       this.totalRecibo = totalRecibo;
       this.exencion = exencion;
       this.bonificacion = bonificacion;
       this.email = email;
       this.ayuntamiento = ayuntamiento;
    }
   
    public int getNumRecibo() {
        return this.numRecibo;
    }
    
    public void setNumRecibo(int numRecibo) {
        this.numRecibo = numRecibo;
    }
    public Contribuyente getContribuyente() {
        return this.contribuyente;
    }
    
    public void setContribuyente(Contribuyente contribuyente) {
        this.contribuyente = contribuyente;
    }
    public Vehiculos getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Vehiculos vehiculos) {
        this.vehiculos = vehiculos;
    }
    public Date getFechaPadron() {
        return this.fechaPadron;
    }
    
    public void setFechaPadron(Date fechaPadron) {
        this.fechaPadron = fechaPadron;
    }
    public Date getFechaRecibo() {
        return this.fechaRecibo;
    }
    
    public void setFechaRecibo(Date fechaRecibo) {
        this.fechaRecibo = fechaRecibo;
    }
    public String getNifContribuyente() {
        return this.nifContribuyente;
    }
    
    public void setNifContribuyente(String nifContribuyente) {
        this.nifContribuyente = nifContribuyente;
    }
    public String getDireccionCompleta() {
        return this.direccionCompleta;
    }
    
    public void setDireccionCompleta(String direccionCompleta) {
        this.direccionCompleta = direccionCompleta;
    }
    public String getIban() {
        return this.iban;
    }
    
    public void setIban(String iban) {
        this.iban = iban;
    }
    public String getTipoVehiculo() {
        return this.tipoVehiculo;
    }
    
    public void setTipoVehiculo(String tipoVehiculo) {
        this.tipoVehiculo = tipoVehiculo;
    }
    public String getMarcaModelo() {
        return this.marcaModelo;
    }
    
    public void setMarcaModelo(String marcaModelo) {
        this.marcaModelo = marcaModelo;
    }
    public String getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(String unidad) {
        this.unidad = unidad;
    }
    public double getValorUnidad() {
        return this.valorUnidad;
    }
    
    public void setValorUnidad(double valorUnidad) {
        this.valorUnidad = valorUnidad;
    }
    public double getTotalRecibo() {
        return this.totalRecibo;
    }
    
    public void setTotalRecibo(double totalRecibo) {
        this.totalRecibo = totalRecibo;
    }
    public Character getExencion() {
        return this.exencion;
    }
    
    public void setExencion(Character exencion) {
        this.exencion = exencion;
    }
    public double getBonificacion() {
        return this.bonificacion;
    }
    
    public void setBonificacion(double bonificacion) {
        this.bonificacion = bonificacion;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAyuntamiento() {
        return this.ayuntamiento;
    }
    
    public void setAyuntamiento(String ayuntamiento) {
        this.ayuntamiento = ayuntamiento;
    }




}


