package POJOS;
// Generated 05-mar-2025 14:16:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculos generated by hbm2java
 */
public class Vehiculos  implements java.io.Serializable {


     private int idVehiculo;
     private Contribuyente contribuyente;
     private Ordenanza ordenanza;
     private String tipo;
     private String marca;
     private String modelo;
     private String matricula;
     private String numeroBastidor;
     private Double caballosFiscales;
     private Double plazas;
     private Double centimetroscubicos;
     private Double kgcarga;
     private Character exencion;
     private Date fechaMatriculacion;
     private Date fechaAlta;
     private Date fechaBaja;
     private Date fechaBajaTemporal;
     private Set reciboses = new HashSet(0);

    public Vehiculos() {
    }

	
    public Vehiculos(int idVehiculo, Contribuyente contribuyente, Ordenanza ordenanza, String tipo, String marca, String modelo, String matricula, String numeroBastidor, Date fechaMatriculacion, Date fechaAlta) {
        this.idVehiculo = idVehiculo;
        this.contribuyente = contribuyente;
        this.ordenanza = ordenanza;
        this.tipo = tipo;
        this.marca = marca;
        this.modelo = modelo;
        this.matricula = matricula;
        this.numeroBastidor = numeroBastidor;
        this.fechaMatriculacion = fechaMatriculacion;
        this.fechaAlta = fechaAlta;
    }
    public Vehiculos(int idVehiculo, Contribuyente contribuyente, Ordenanza ordenanza, String tipo, String marca, String modelo, String matricula, String numeroBastidor, Double caballosFiscales, Double plazas, Double centimetroscubicos, Double kgcarga, Character exencion, Date fechaMatriculacion, Date fechaAlta, Date fechaBaja, Date fechaBajaTemporal, Set reciboses) {
       this.idVehiculo = idVehiculo;
       this.contribuyente = contribuyente;
       this.ordenanza = ordenanza;
       this.tipo = tipo;
       this.marca = marca;
       this.modelo = modelo;
       this.matricula = matricula;
       this.numeroBastidor = numeroBastidor;
       this.caballosFiscales = caballosFiscales;
       this.plazas = plazas;
       this.centimetroscubicos = centimetroscubicos;
       this.kgcarga = kgcarga;
       this.exencion = exencion;
       this.fechaMatriculacion = fechaMatriculacion;
       this.fechaAlta = fechaAlta;
       this.fechaBaja = fechaBaja;
       this.fechaBajaTemporal = fechaBajaTemporal;
       this.reciboses = reciboses;
    }
   
    public int getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(int idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    public Contribuyente getContribuyente() {
        return this.contribuyente;
    }
    
    public void setContribuyente(Contribuyente contribuyente) {
        this.contribuyente = contribuyente;
    }
    public Ordenanza getOrdenanza() {
        return this.ordenanza;
    }
    
    public void setOrdenanza(Ordenanza ordenanza) {
        this.ordenanza = ordenanza;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public String getNumeroBastidor() {
        return this.numeroBastidor;
    }
    
    public void setNumeroBastidor(String numeroBastidor) {
        this.numeroBastidor = numeroBastidor;
    }
    public Double getCaballosFiscales() {
        return this.caballosFiscales;
    }
    
    public void setCaballosFiscales(Double caballosFiscales) {
        this.caballosFiscales = caballosFiscales;
    }
    public Double getPlazas() {
        return this.plazas;
    }
    
    public void setPlazas(Double plazas) {
        this.plazas = plazas;
    }
    public Double getCentimetroscubicos() {
        return this.centimetroscubicos;
    }
    
    public void setCentimetroscubicos(Double centimetroscubicos) {
        this.centimetroscubicos = centimetroscubicos;
    }
    public Double getKgcarga() {
        return this.kgcarga;
    }
    
    public void setKgcarga(Double kgcarga) {
        this.kgcarga = kgcarga;
    }
    public Character getExencion() {
        return this.exencion;
    }
    
    public void setExencion(Character exencion) {
        this.exencion = exencion;
    }
    public Date getFechaMatriculacion() {
        return this.fechaMatriculacion;
    }
    
    public void setFechaMatriculacion(Date fechaMatriculacion) {
        this.fechaMatriculacion = fechaMatriculacion;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }
    public Date getFechaBajaTemporal() {
        return this.fechaBajaTemporal;
    }
    
    public void setFechaBajaTemporal(Date fechaBajaTemporal) {
        this.fechaBajaTemporal = fechaBajaTemporal;
    }
    public Set getReciboses() {
        return this.reciboses;
    }
    
    public void setReciboses(Set reciboses) {
        this.reciboses = reciboses;
    }




}


